### ISSUE TITLE
后端程序bug

### ISSUE THREAD

**Issue by 415400396** [shimh-develop/blog-vue-springboot#23]
你好，我使用spring-tool-suite 4.6.1，我用shiro框架的时候好像无法导入DefaultWebSecurityManager
`import org.apache.shiro.web.servlet.ShiroHttpServletRequest;
import org.apache.shiro.web.session.mgt.DefaultWebSessionManager;
import org.apache.shiro.web.util.WebUtils;`

**Comment by shimh-develop** [comment]
@415400396 shiro的jar没导入吧，更新下maven依赖

**Comment by 415400396** [comment]
嗯嗯我成功运行了，非常感谢，代码结构清晰，很值得学习。
